### PR TITLE
Add align support

### PR DESCRIPTION
**Pull request by sebkur**
I added method `public ASCIITable align(int column, Align align)` that allows us to set the alignment of a column (by index) to `Align.RIGHT`. I also added a corresponding test.

This is the test example, with column 2 set to `Align.RIGHT`.

```
+=====+==============+=====================+
| ID  | Name         | Email               |
|=====|==============|=====================|
| 123 | Alfred Alan  |     aalan@gmail.com |
|-----|--------------|---------------------|
| 223 | Alison Smart |    asmart@gmail.com |
|-----|--------------|---------------------|
| 256 | Ben Bessel   |    benb@outlook.com |
|-----|--------------|---------------------|
| 374 | John Roberts | johnrob@company.com |
+=====+==============+=====================+
```

Note that I took care not to right-align the header. It's a personal preference, I think it looks better if it is not aligned to the right. Added the disambiguating boolean argument `isHeader`  to `appendRow()` in order to do that. We could make that configurable, too.

## Some notes

* Implementing `Align.CENTER` will be a bit more tricky. We either  to deal with odd number of padding characters where we cannot pad with the same amount of whitespace on each side of the cell's content.
* I think it could also make sense to add variant `align(String columnName, Align align)` with column names as argument. Could also be tricky because we can't really assume column names are unique.

### CODE REVIEW

**Comment by MitchTalmadge** [comment]
Wow cool, very well done! Ignore the build error. Do you think it would be a good idea to change the name of the function from `align` to `alignColumn` so that later we could add an `alignCell` function for alignment of a single cell? I think that'd be a nice addition. 

Thanks for the contribution!

**Comment by sebkur** [comment]
Yes, I think renaming to `alignColumn` makes sense. I'll update the PR

**Comment by sebkur** [comment]
I pushed a new version a few days ago in case you didn't notice (not sure if you receive a notification about new pushes to my branch)

**Comment by MitchTalmadge** [comment]
My apologies, I got caught up in work. It looks good!

**Comment by sebkur** [comment]
Would you make a new release or do you want to wait for more features?

**Comment by MitchTalmadge** [comment]
Deployed as version 1.4.0, thanks for reminding me!

**Comment by sebkur** [comment]
Thank you

**Pull request merged**
